import type { ResumeThemeConfig } from '@/themes/types'

const theme: ResumeThemeConfig = {
  key: 'modern-clarity',
  name: '现代简约',
  description: '清爽单栏与柔和配色，信息间距更紧凑，适合应届技术岗位投递。',
  category: '现代简约',
  audience: '应届开发岗 / 前端 / 全栈 / 互联网团队',
  previewTags: ['简洁明快', '紧凑阅读', '单栏稳定'],
  order: 3,
  palette: {
    primary: '#1d4ed8',
    secondary: '#2563eb',
    accent: '#0f766e',
    canvas: '#eef4ff',
    paper: '#fbfdff',
    text: '#162033',
    mutedText: '#475569',
    subtleText: '#64748b',
    border: '#dbe6f3',
    divider: '#d9e2ef',
    badgeBackground: 'rgba(37, 99, 235, 0.1)',
    badgeText: '#1d4ed8',
    toolbarBackground: 'rgba(251, 253, 255, 0.94)',
    toolbarText: '#162033',
    buttonBackground: '#fbfdff',
    buttonText: '#162033',
    shadow: '0 28px 60px rgba(29, 78, 216, 0.12)',
  },
  layout: {
    columns: 1,
    sidebarWidth: '0px',
    profileVariant: 'hero',
    sectionTitleStyle: 'divider',
    sectionOrder: ['profile', 'experience', 'projects', 'education', 'awards'],
    sidebarSections: [],
    paperPadding: '22px 26px',
    shellGap: '8px',
    columnGap: '0px',
    blockGap: '9px',
    sectionGap: '7px',
    paperRadius: '12px',
  },
  defaults: {
    resumeSize: 'standard',
    backgroundColor: '#fbfdff',
    preserveExportBackground: true,
  },
}

export default theme
