import type { ResumeThemeConfig } from '@/themes/types'

const theme: ResumeThemeConfig = {
  key: 'professional-balance',
  name: '稳重专业',
  description: '克制的单栏专业排版，强化层级与可读性，适合校招研发岗位。',
  category: '稳重专业',
  audience: '校招研发岗 / 大厂投递 / 硕博技术岗位',
  previewTags: ['专业克制', '层级清晰', '阅读友好'],
  order: 2,
  palette: {
    primary: '#0f3b66',
    secondary: '#1f5f8b',
    accent: '#2a7f62',
    canvas: '#eaf0f5',
    paper: '#ffffff',
    text: '#12202f',
    mutedText: '#415467',
    subtleText: '#6f8091',
    border: '#d9e2ea',
    divider: '#d2dbe4',
    badgeBackground: 'rgba(15, 59, 102, 0.08)',
    badgeText: '#0f3b66',
    toolbarBackground: 'rgba(255, 255, 255, 0.94)',
    toolbarText: '#12202f',
    buttonBackground: '#ffffff',
    buttonText: '#12202f',
    shadow: '0 24px 48px rgba(15, 59, 102, 0.12)',
  },
  layout: {
    columns: 1,
    sidebarWidth: '0px',
    profileVariant: 'hero',
    sectionTitleStyle: 'divider',
    sectionOrder: ['profile', 'education', 'experience', 'projects', 'awards'],
    sidebarSections: [],
    paperPadding: '22px 26px',
    shellGap: '8px',
    columnGap: '0px',
    blockGap: '9px',
    sectionGap: '7px',
    paperRadius: '10px',
  },
  defaults: {
    resumeSize: 'standard',
    backgroundColor: '#ffffff',
    preserveExportBackground: true,
  },
}

export default theme
