import type { ResumeThemeConfig } from '@/themes/types'

const theme: ResumeThemeConfig = {
  key: 'tech-grid',
  name: '技术导向',
  description: '突出项目与经历的技术风单栏布局，强调关键贡献与实现细节。',
  category: '技术导向',
  audience: '研发工程师 / 算法工程师 / 研究型硕博',
  previewTags: ['项目优先', '技术表达强', '结构紧凑'],
  order: 4,
  palette: {
    primary: '#0f172a',
    secondary: '#1e293b',
    accent: '#0ea5e9',
    canvas: '#e2e8f0',
    paper: '#f8fafc',
    text: '#0f172a',
    mutedText: '#334155',
    subtleText: '#64748b',
    border: '#cbd5e1',
    divider: '#d8e1ea',
    badgeBackground: 'rgba(14, 165, 233, 0.12)',
    badgeText: '#0369a1',
    toolbarBackground: 'rgba(248, 250, 252, 0.94)',
    toolbarText: '#0f172a',
    buttonBackground: '#f8fafc',
    buttonText: '#0f172a',
    shadow: '0 30px 70px rgba(15, 23, 42, 0.14)',
  },
  layout: {
    columns: 1,
    sidebarWidth: '0px',
    profileVariant: 'hero',
    sectionTitleStyle: 'divider',
    sectionOrder: ['profile', 'projects', 'experience', 'education', 'awards'],
    sidebarSections: [],
    paperPadding: '22px 26px',
    shellGap: '8px',
    columnGap: '0px',
    blockGap: '9px',
    sectionGap: '7px',
    paperRadius: '10px',
  },
  defaults: {
    resumeSize: 'standard',
    backgroundColor: '#f8fafc',
    preserveExportBackground: true,
  },
}

export default theme
